// This file has been generated by Tauri Specta. Do not edit this file manually.

/**
 * @typedef {import("./kitchen_sink")} kitchen_sink
 */

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  A command with a doc comment.
	 * @param {string} myName
	 * @returns {Promise<string>}
	 */
	greet: (myName) => __TAURI_INVOKE("greet", { myName }),
	/** @returns {Promise<void>} */
	unitCommand: () => __TAURI_INVOKE("unit_command"),
	/**
	 * @param {number} delayMs
	 * @returns {Promise<number>}
	 */
	asyncCommand: (delayMs) => __TAURI_INVOKE("async_command", { delayMs }),
	/**
	 * @param {string} a
	 * @param {number} b
	 * @param {boolean} c
	 * @param {string[]} d
	 * @param {string | null} e
	 * @returns {Promise<boolean>}
	 */
	manyArgs: (a, b, c, d, e) => __TAURI_INVOKE("many_args", { a, b, c, d, e }),
	/**
	 * @param {kitchen_sink.Profile} profile
	 * @returns {Promise<kitchen_sink.Profile>}
	 */
	echoProfile: (profile) => __TAURI_INVOKE("echo_profile", { profile }),
	/**
	 * @param {kitchen_sink.Point} point
	 * @returns {Promise<kitchen_sink.Wrapper>}
	 */
	tupleTypes: (point) => __TAURI_INVOKE("tuple_types", { point }),
	/**
	 * @param {kitchen_sink.TaggedEnum} tagged
	 * @param {kitchen_sink.UntaggedEnum} untagged
	 * @returns {Promise<kitchen_sink.TaggedEnum>}
	 */
	enums: (tagged, untagged) => __TAURI_INVOKE("enums", { tagged, untagged }),
	/**
	 * @param {kitchen_sink.PhaseSpecificRename_Deserialize} input
	 * @returns {Promise<kitchen_sink.PhaseSpecificRename_Serialize>}
	 */
	phaseSpecificRename: (input) => __TAURI_INVOKE("phase_specific_rename", { input }),
	/** @returns {Promise<{ status: "ok"; data: string } | { status: "error"; error: kitchen_sink.PlainError }>} */
	plainError: () => typedError(__TAURI_INVOKE("plain_error")),
	/** @returns {Promise<{ status: "ok"; data: kitchen_sink.Profile } | { status: "error"; error: kitchen_sink.TaggedError }>} */
	taggedError: () => typedError(__TAURI_INVOKE("tagged_error")),
	/** @returns {Promise<{ status: "ok"; data: string | null } | { status: "error"; error: kitchen_sink.PlainError }>} */
	nullableResult: () => typedError(__TAURI_INVOKE("nullable_result")),
	/** @returns {Promise<string | null>} */
	maybe: () => __TAURI_INVOKE("maybe"),
	/**
	 * @param {Channel<number>} channel
	 * @returns {Promise<void>}
	 */
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
	/**
	 * @param {string} visible
	 * @returns {Promise<string>}
	 */
	skippedArgs: (visible) => __TAURI_INVOKE("skipped_args", { visible }),
	/** @returns {Promise<void>} */
	generic: () => __TAURI_INVOKE("generic"),
	/**
	 * @returns {Promise<void>}
	 * @deprecated This is a deprecated command
	 */
	deprecatedCommand: () => __TAURI_INVOKE("deprecated_command"),
};

/** Events */
export const events = {
	/** @type {ReturnType<typeof makeEvent<kitchen_sink.EmptyEvent>>} */
	emptyEvent: makeEvent("empty-event"),
	/** @type {ReturnType<typeof makeEvent<kitchen_sink.MessageEvent>>} */
	messageEvent: makeEvent("message-event"),
	/** @type {ReturnType<typeof makeEvent<kitchen_sink.StructEvent>>} */
	structEvent: makeEvent("struct-event"),
};

/* Constants */
export const APP_NAME = "Kitchen Sink";

export const DEBUG_DEFAULT = false;

export const MAX_RETRIES = 3;

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 * @param {(payload: T) => unknown} [serialize]
 * @param {(payload: any) => T} [deserialize]
 */
function makeEvent(name, serialize, deserialize) {
    const mapEvent = (cb) => (event) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload) => serialize ? serialize(payload) : payload;

    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, mapPayload(payload)),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, mapPayload(payload)),
    });

    return Object.assign(fn, base);
}
