// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	* @typedef {null} EmptyEvent
	*
	*  Registered via `Builder::typ` without being referenced by a command.
	*
	* @typedef {{
	*		name: string,
	*	}} ManuallyRegistered
	* @property {string} name
	*
	* @typedef {string} MessageEvent
	* @property {string} "0"
	*
	* @typedef {PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize} PhaseSpecificRename
	* @property {PhaseSpecificRename_Serialize} Serialize
	* @property {PhaseSpecificRename_Deserialize} Deserialize
	*
	* @typedef {{
	*		deserialized_value: string,
	*	}} PhaseSpecificRename_Deserialize
	* @property {string} deserialized_value
	*
	* @typedef {{
	*		serialized_value: string,
	*	}} PhaseSpecificRename_Serialize
	* @property {string} serialized_value
	*
	* @typedef {"NotFound" | { PermissionDenied: string }} PlainError
	* @property {"NotFound"} NotFound
	* @property {{ PermissionDenied: string }} PermissionDenied
	*
	* @typedef {[number | null, number | null]} Point
	* @property {number | null} "0"
	* @property {number | null} "1"
	*
	*  A struct with a doc comment and common field shapes.
	*
	* @typedef {{
	*		userId: number,
	*		displayName: string,
	*		tags: string[],
	*		homepage: string | null,
	*		scores: { [key in string]: number },
	*	}} Profile
	* @property {number} userId
	* @property {string} displayName
	* @property {string[]} tags
	* @property {string | null} homepage
	* @property {{ [key in string]: number }} scores
	*
	* @typedef {{
	*		eventId: number,
	*		payload: string,
	*	}} StructEvent
	* @property {number} eventId
	* @property {string} payload
	*
	* @typedef {{ type: "Unit" } | { type: "Tuple"; data: string } | { type: "Struct"; data: {
	* 	id: number,
	* } }} TaggedEnum
	* @property {{ type: "Unit" }} Unit
	* @property {{ type: "Tuple"; data: string }} Tuple
	* @property {{ type: "Struct"; data: {
	* 	id: number,
	* } }} Struct
	*
	* @typedef {{ type: "Io"; data: string } | { type: "Parse"; data: {
	* 	line: number,
	* } }} TaggedError
	* @property {{ type: "Io"; data: string }} Io
	* @property {{ type: "Parse"; data: {
	* 	line: number,
	* } }} Parse
	*
	* @typedef {number | string} UntaggedEnum
	* @property {number} Number
	* @property {string} Text
	*
	* @typedef {string} Wrapper
	* @property {string} "0"
	*/
