// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 * @param {BigNumbers} input
	 * @returns {Promise<BigNumbers>}
	 */
	bigNumbers: (input) => __TAURI_INVOKE("big_numbers", { input }),
};

/* Types */
/**
	* @typedef {{
	*		unsigned: number,
	*		signed: number,
	*	}} BigNumbers
	* @property {number} unsigned
	* @property {number} signed
	*/

