// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import { queryOptions as __TANSTACK_QUERY_OPTIONS, mutationOptions as __TANSTACK_MUTATION_OPTIONS } from "@tanstack/react-query";

/** Commands */
export const commands = {
	greeting: (name: string) => __TANSTACK_QUERY_OPTIONS({ queryKey: ["greeting", { name }] as const, queryFn: () => __TAURI_INVOKE<string>("greeting", { name }) }),
	listTodos: () => __TANSTACK_QUERY_OPTIONS({ queryKey: ["list_todos"] as const, queryFn: () => __TAURI_INVOKE<Todo[]>("list_todos") }),
	createTodo: (title: string) => __TANSTACK_MUTATION_OPTIONS({ mutationKey: ["create_todo", { title }] as const, mutationFn: () => __TAURI_INVOKE<Todo>("create_todo", { title }) }),
	deleteTodo: (id: number) => __TANSTACK_MUTATION_OPTIONS({ mutationKey: ["delete_todo", { id }] as const, mutationFn: () => __TAURI_INVOKE<boolean>("delete_todo", { id }) }),
};

/* Types */
export type Todo = {
	id: number,
	title: string,
};

