// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  HELLO
	 *  WORLD
	 *  !!!!
	 * @param {string} myName
	 * @returns {string} myName
	 */
	helloWorld: (myName) => __TAURI_INVOKE("hello_world", { myName }),
	/** @returns {string} myName */
	goodbyeWorld: () => __TAURI_INVOKE("goodbye_world"),
	/**
	 * @param {string} myName
	 * @returns {string} myName
	 */
	asyncHelloWorld: (myName) => __TAURI_INVOKE("async_hello_world", { myName }),
	/** @returns {string} myName */
	hasError: () => typedError(__TAURI_INVOKE("has_error")),
	/** @returns {string} myName */
	someStruct: () => __TAURI_INVOKE("some_struct"),
	/** @returns {string} myName */
	generic: () => __TAURI_INVOKE("generic"),
	/**
	 * @returns {string} myName
	 * @deprecated This is a deprecated function
	 */
	deprecated: () => __TAURI_INVOKE("deprecated"),
	/**
	 * @param {Channel<number>} channel
	 * @returns {string} myName
	 */
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
	/**
	 * @param {PhaseSpecificRename_Deserialize} input
	 * @returns {string} myName
	 */
	phaseSpecificRename: (input) => __TAURI_INVOKE("phase_specific_rename", { input }),
	/** @returns {string} myName */
	typesafeErrorsUsingThiserror: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	/** @returns {string} myName */
	typesafeErrorsUsingThiserrorWithValue: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
	/**
	 * @param {SemanticTypes} arg
	 * @param {Channel<SemanticTypes>} channel
	 * @returns {string} myName
	 */
	semanticTypes: (arg, channel) => __TAURI_INVOKE("semantic_types", { arg: ({...arg,bytes:[...arg.bytes]}), channel }).then((v) => (({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)}) as typeof v)),
};

/** Events */
export const events = {
	/** @type {ReturnType<typeof makeEvent<EmptyEvent>>} */
	emptyEvent: makeEvent("empty-event"),
	/** @type {ReturnType<typeof makeEvent<DemoEvent>>} */
	myDemoEvent: makeEvent("myDemoEvent"),
	/** @type {ReturnType<typeof makeEvent<SemanticTypesEvent>>} */
	semanticTypesEvent: makeEvent("semantic-types-event", (v) => ({...v,bytes:[...v.bytes]}), (v) => ({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)})),
};

/* Constants */
export const universalConstant = 42;

/* Types */
/**
	* @typedef {string} Custom
	* @property {string} "0"
	*
	* @typedef {string} DemoEvent
	* @property {string} "0"
	*
	* @typedef {null} EmptyEvent
	*
	* @typedef {{ type: "IoError" } | { type: "AnotherError"; data: string }} MyError
	* @property {{ type: "IoError" }} IoError
	* @property {{ type: "AnotherError"; data: string }} AnotherError
	*
	* @typedef {{ type: "IoError"; data: string }} MyError2
	* @property {{ type: "IoError"; data: string }} IoError
	*
	* @typedef {{
	*		some_field: string,
	*	}} MyStruct
	* @property {string} some_field
	*
	* @typedef {PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize} PhaseSpecificRename
	* @property {PhaseSpecificRename_Serialize} Serialize
	* @property {PhaseSpecificRename_Deserialize} Deserialize
	*
	* @typedef {{
	*		deserialized_value: string,
	*	}} PhaseSpecificRename_Deserialize
	* @property {string} deserialized_value
	*
	* @typedef {{
	*		serialized_value: string,
	*	}} PhaseSpecificRename_Serialize
	* @property {string} serialized_value
	*
	* @typedef {{
	*		date: Date,
	*		bytes: Uint8Array,
	*		url: URL,
	*	}} SemanticTypes
	* @property {Date} date
	* @property {Uint8Array} bytes
	* @property {URL} url
	*
	* @typedef {{
	*		date: Date,
	*		bytes: Uint8Array,
	*		url: URL,
	*	}} SemanticTypesEvent
	* @property {Date} date
	* @property {Uint8Array} bytes
	* @property {URL} url
	*
	* @typedef {{
	*		a: string,
	*	}} Testing
	* @property {string} a
	*/

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 * @param {(payload: T) => unknown} [serialize]
 * @param {(payload: any) => T} [deserialize]
 */
function makeEvent(name, serialize, deserialize) {
    const mapEvent = (cb) => (event) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload) => serialize ? serialize(payload) : payload;

    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, mapPayload(payload)),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, mapPayload(payload)),
    });

    return Object.assign(fn, base);
}

