// This file has been generated by Tauri Specta. Do not edit this file manually.
import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';

/* Commands */
export const commands = { 
	helloWorld: () => __TAURI_INVOKE<string>("hello_world", ),
};

/* Constants */
export const bruh = 42 as const;

export const universalConstant = 42 as const;

/* Types */
export type Custom = string;

export type Testing = { 
		a: string,
	};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ Ok: T } | { Error: E }> {
  return await result as any; // TODO
}

