// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  HELLO
	 *  WORLD
	 *  !!!!
	 */
	helloWorld: (myName: string) => __TAURI_INVOKE<string>("hello_world", { myName }),
	goodbyeWorld: () => __TAURI_INVOKE<string>("goodbye_world"),
	asyncHelloWorld: (myName: string) => __TAURI_INVOKE<string>("async_hello_world", { myName }),
	hasError: () => typedError<string, number>(__TAURI_INVOKE("has_error")),
	someStruct: () => __TAURI_INVOKE<$s$.tauri_specta_example_app.nested.MyStruct>("some_struct"),
	generic: () => __TAURI_INVOKE<void>("generic"),
	/**
	 * @deprecated This is a deprecated function
	 */
	deprecated: () => __TAURI_INVOKE<void>("deprecated"),
	withChannel: (channel: Channel<number>) => __TAURI_INVOKE<void>("with_channel", { channel }),
	typesafeErrorsUsingThiserror: () => typedError<null, $s$.tauri_specta_example_app.MyError>(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	typesafeErrorsUsingThiserrorWithValue: () => typedError<null, $s$.tauri_specta_example_app.MyError2>(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
};

/** Events */
export const events = {
	/**
	 * @type {ReturnType<typeof makeEvent<$s$.tauri_specta_example_app.EmptyEvent>>}
	 */
	emptyEvent: makeEvent<$s$.tauri_specta_example_app.EmptyEvent>("empty-event"),
	/**
	 * @type {ReturnType<typeof makeEvent<$s$.tauri_specta_example_app.DemoEvent>>}
	 */
	myDemoEvent: makeEvent<$s$.tauri_specta_example_app.DemoEvent>("myDemoEvent"),
};

/* Constants */
export const universalConstant = 42 as const;

/* Types */
namespace $s$ {

	export namespace tauri_specta_example_app {

		export type Custom = string;

		export type DemoEvent = string;

		export type EmptyEvent = null;

		export type MyError = { type: "IoError" } | { type: "AnotherError"; data: string };

		export type MyError2 = { type: "IoError"; data: string };

		export type Testing = {
			a: string,
		};

		export namespace nested {

			export type MyStruct = {
				some_field: string,
			};
		}
	}
}
export import tauri_specta_example_app = $s$.tauri_specta_example_app;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

