// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	helloWorld: (myName) => __TAURI_INVOKE("hello_world", { myName }),
	goodbyeWorld: () => __TAURI_INVOKE("goodbye_world"),
	asyncHelloWorld: (myName) => __TAURI_INVOKE("async_hello_world", { myName }),
	hasError: () => typedError(__TAURI_INVOKE("has_error")),
	someStruct: () => __TAURI_INVOKE("some_struct"),
	generic: () => __TAURI_INVOKE("generic"),
	deprecated: () => __TAURI_INVOKE("deprecated"),
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
	typesafeErrorsUsingThiserror: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	typesafeErrorsUsingThiserrorWithValue: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
};

/** Events */
export const events = {
	emptyEvent: makeEvent("empty-event"),
	myDemoEvent: makeEvent("myDemoEvent"),
};

/* Constants */
export const universalConstant = 42;

/* Types */
/**
	* @typedef {string} Custom
	* @property {string} "0"
	*
	* @typedef {string} DemoEvent
	* @property {string} "0"
	*
	* @typedef {null} EmptyEvent
	*
	* @typedef {{ type: "IoError" } | { type: "AnotherError"; data: string }} MyError
	* @property {{ type: "IoError" }} IoError
	* @property {{ type: "AnotherError"; data: string }} AnotherError
	*
	* @typedef {{ type: "IoError"; data: string }} MyError2
	* @property {{ type: "IoError"; data: string }} IoError
	*
	* @typedef {{
	*		some_field: string,
	*	}} MyStruct
	* @property {string} some_field
	*
	* @typedef {{
	*		a: string,
	*	}} Testing
	* @property {string} a
	*/

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 */
function makeEvent(name) {
    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, cb),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, cb),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, payload),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, cb),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, cb),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, payload),
    });

    return Object.assign(fn, base);
}

