// eslint-disable
// This file has been generated by Tauri Specta. DO NOT EDIT.
import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';


export type Custom = string;


export type DemoEvent = string;


export type EmptyEvent = null;


export type MyError = { type: "IoError" } | { type: "AnotherError"; data: string };


export type MyError2 = { type: "IoError"; data: string };


export type MyStruct = {
		some_field: string;
	};

async function typedError<T, E>(result: Promise<T>): Promise<{ Ok: T } | { Error: E }> {
  return await result as any; // TODO
}

export const commands = {
	helloWorld: () => typedError<any, any>(__TAURI_INVOKE("hello_world")),
	goodbyeWorld: () => typedError<any, any>(__TAURI_INVOKE("goodbye_world")),
	asyncHelloWorld: () => typedError<any, any>(__TAURI_INVOKE("async_hello_world")),
	hasError: () => typedError<any, any>(__TAURI_INVOKE("has_error")),
	someStruct: () => typedError<any, any>(__TAURI_INVOKE("some_struct")),
	generic: () => __TAURI_INVOKE<any>("generic"),
	deprecated: () => __TAURI_INVOKE<any>("deprecated"),
	typesafeErrorsUsingThiserror: () => typedError<any, any>(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	typesafeErrorsUsingThiserrorWithValue: () => typedError<any, any>(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
}
