// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  HELLO
	 *  WORLD
	 *  !!!!
	 */
	helloWorld: (myName: string) => __TAURI_INVOKE<string>("hello_world", { myName }),
	goodbyeWorld: () => __TAURI_INVOKE<string>("goodbye_world"),
	asyncHelloWorld: (myName: string) => __TAURI_INVOKE<string>("async_hello_world", { myName }),
	hasError: () => typedError<string, number>(__TAURI_INVOKE("has_error")),
	addBigNumbers: (a: bigint, b: bigint) => __TAURI_INVOKE<bigint>("add_big_numbers", { a, b }).then((v) => __TS_transform(v, {"t":"big_int"})),
	someStruct: () => __TAURI_INVOKE<MyStruct>("some_struct"),
	generic: () => __TAURI_INVOKE<void>("generic"),
	/**
	 * @deprecated This is a deprecated function
	 */
	deprecated: () => __TAURI_INVOKE<void>("deprecated"),
	withChannel: (channel: Channel<number>) => __TAURI_INVOKE<void>("with_channel", { channel }),
	typesafeErrorsUsingThiserror: () => typedError<null, MyError>(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	typesafeErrorsUsingThiserrorWithValue: () => typedError<null, MyError2>(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
};

/** Events */
export const events = {
	emptyEvent: makeEvent<EmptyEvent>("empty-event"),
	myDemoEvent: makeEvent<DemoEvent>("myDemoEvent"),
};

/* Constants */
export const universalConstant = 42 as const;

/* Types */
export type Custom = string;

export type DemoEvent = string;

export type EmptyEvent = null;

export type MyError = { type: "IoError"; data: { type: "IoError" } } | { type: "AnotherError"; data: string };

export type MyError2 = { type: "IoError"; data: string };

export type MyStruct = {
	some_field: string,
};

export type Testing = {
	a: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

function __TS_transform(value, spec) {
    if (!spec || spec.t === "identity") return value;

    switch (spec.t) {
        case "big_int":
            if (typeof value === "bigint") return value;
            if (typeof value === "number" && Number.isInteger(value)) return BigInt(value);
            return value;
        case "date":
            return typeof value === "string" ? new Date(value) : value;
        case "bytes":
            return Array.isArray(value) && value.every((v) => typeof v === "number") ? Uint8Array.from(value) : value;
        case "nullable":
            return value == null ? value : __TS_transform(value, spec.v);
        case "list":
            return Array.isArray(value) ? value.map((item) => __TS_transform(item, spec.v)) : value;
        case "tuple":
            return Array.isArray(value)
                ? value.map((item, index) => __TS_transform(item, spec.v[index] || { t: "identity" }))
                : value;
        case "object": {
            if (value == null || typeof value !== "object" || Array.isArray(value)) return value;

            let out = value;
            for (const [key, nested] of spec.v) {
                if (!Object.prototype.hasOwnProperty.call(value, key)) continue;
                const next = __TS_transform(value[key], nested);
                if (next !== value[key]) {
                    if (out === value) out = { ...value };
                    out[key] = next;
                }
            }
            return out;
        }
        case "map": {
            if (value == null || typeof value !== "object" || Array.isArray(value)) return value;

            let out = value;
            for (const key of Object.keys(value)) {
                const next = __TS_transform(value[key], spec.v);
                if (next !== value[key]) {
                    if (out === value) out = { ...value };
                    out[key] = next;
                }
            }
            return out;
        }
        case "enum":
            return __TS_transformEnum(value, spec.v);
        default:
            return value;
    }
}

function __TS_transformEnum(value, variants) {
    for (const variant of variants) {
        const transformed = __TS_transformEnumVariant(value, variant);
        if (transformed !== undefined) return transformed;
    }
    return value;
}

function __TS_transformEnumVariant(value, variant) {
    if (variant.kind === "unit") return undefined;

    if (value != null && typeof value === "object" && !Array.isArray(value)) {
        if (Object.prototype.hasOwnProperty.call(value, variant.name)) {
            const next = __TS_transform(value[variant.name], variant.spec);
            if (next === value[variant.name]) return value;
            return { ...value, [variant.name]: next };
        }

        if (value.type === variant.name && Object.prototype.hasOwnProperty.call(value, "data")) {
            const next = __TS_transform(value.data, variant.spec);
            if (next === value.data) return value;
            return { ...value, data: next };
        }

        if (value.tag === variant.name && Object.prototype.hasOwnProperty.call(value, "content")) {
            const next = __TS_transform(value.content, variant.spec);
            if (next === value.content) return value;
            return { ...value, content: next };
        }
    }

    const direct = __TS_transform(value, variant.spec);
    if (direct !== value) return direct;

    return undefined;
}

function __TS_transformResult(result, okSpec, errSpec) {
    return result.then((value) => {
        if (value?.status === "ok") {
            return { status: "ok", data: __TS_transform(value.data, okSpec) };
        }

        if (value?.status === "error") {
            return { status: "error", error: __TS_transform(value.error, errSpec) };
        }

        return value;
    });
}

