// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";
import type { Webview } from "@tauri-apps/api/webview";
import type { Window } from "@tauri-apps/api/window";

/** Commands */
export const commands = {
	helloWorld: (myName: string) => __TAURI_INVOKE<string>("hello_world", { myName }),
	hasError: () => typedError<string, number>(__TAURI_INVOKE("has_error")),
	deprecated: () => __TAURI_INVOKE<void>("deprecated"),
	withChannel: (channel: $s$.tauri.ipc.channel.TAURI_CHANNEL<number>) => __TAURI_INVOKE<void>("with_channel", { channel }),
};

/** Events */
export const events = {
	emptyEvent: makeEvent<$s$.tauri_specta_example_app.EmptyEvent>("empty-event"),
	myDemoEvent: makeEvent<$s$.tauri_specta_example_app.DemoEvent>("myDemoEvent"),
};

/* Constants */
export const universalConstant = 42 as const;

/* Types */
namespace $s$ {

	export namespace tauri {

		export namespace ipc {

			export namespace channel {

			export type TAURI_CHANNEL<TSend> = null;
}
}
}

	export namespace tauri_specta_example_app {

	export type Custom = string;

	export type DemoEvent = string;

	export type EmptyEvent = null;

	export type Testing = {
		a: string,
	};
}
}
export import tauri = $s$.tauri;
export import tauri_specta_example_app = $s$.tauri_specta_example_app;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: Webview | Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

