// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  A command with a doc comment.
	 * @param {string} myName
	 * @returns {Promise<string>}
	 */
	greet: (myName) => __TAURI_INVOKE("greet", { myName }),
	/** @returns {Promise<void>} */
	unitCommand: () => __TAURI_INVOKE("unit_command"),
	/**
	 * @param {number} delayMs
	 * @returns {Promise<number>}
	 */
	asyncCommand: (delayMs) => __TAURI_INVOKE("async_command", { delayMs }),
	/**
	 * @param {string} a
	 * @param {number} b
	 * @param {boolean} c
	 * @param {string[]} d
	 * @param {string | null} e
	 * @returns {Promise<boolean>}
	 */
	manyArgs: (a, b, c, d, e) => __TAURI_INVOKE("many_args", { a, b, c, d, e }),
	/**
	 * @param {Profile} profile
	 * @returns {Promise<Profile>}
	 */
	echoProfile: (profile) => __TAURI_INVOKE("echo_profile", { profile }),
	/**
	 * @param {Point} point
	 * @returns {Promise<Wrapper>}
	 */
	tupleTypes: (point) => __TAURI_INVOKE("tuple_types", { point }),
	/**
	 * @param {TaggedEnum} tagged
	 * @param {UntaggedEnum} untagged
	 * @returns {Promise<TaggedEnum>}
	 */
	enums: (tagged, untagged) => __TAURI_INVOKE("enums", { tagged, untagged }),
	/**
	 * @param {PhaseSpecificRename_Deserialize} input
	 * @returns {Promise<PhaseSpecificRename_Serialize>}
	 */
	phaseSpecificRename: (input) => __TAURI_INVOKE("phase_specific_rename", { input }),
	/** @returns {Promise<{ data: string; error: null } | { data: null; error: PlainError }>} */
	plainError: () => typedError(__TAURI_INVOKE("plain_error")),
	/** @returns {Promise<{ data: Profile; error: null } | { data: null; error: TaggedError }>} */
	taggedError: () => typedError(__TAURI_INVOKE("tagged_error")),
	/** @returns {Promise<{ data: string | null; error: null } | { data: null; error: PlainError }>} */
	nullableResult: () => typedError(__TAURI_INVOKE("nullable_result")),
	/** @returns {Promise<string | null>} */
	maybe: () => __TAURI_INVOKE("maybe"),
	/**
	 * @param {Channel<number>} channel
	 * @returns {Promise<void>}
	 */
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
	/**
	 * @param {string} visible
	 * @returns {Promise<string>}
	 */
	skippedArgs: (visible) => __TAURI_INVOKE("skipped_args", { visible }),
	/** @returns {Promise<void>} */
	generic: () => __TAURI_INVOKE("generic"),
	/**
	 * @returns {Promise<void>}
	 * @deprecated This is a deprecated command
	 */
	deprecatedCommand: () => __TAURI_INVOKE("deprecated_command"),
};

/** Events */
export const events = {
	/** @type {ReturnType<typeof makeEvent<EmptyEvent>>} */
	emptyEvent: makeEvent("empty-event"),
	/** @type {ReturnType<typeof makeEvent<MessageEvent>>} */
	messageEvent: makeEvent("message-event"),
	/** @type {ReturnType<typeof makeEvent<StructEvent>>} */
	structEvent: makeEvent("struct-event"),
};

/* Constants */
export const APP_NAME = "Kitchen Sink";

export const DEBUG_DEFAULT = false;

export const MAX_RETRIES = 3;

/* Types */
/**
	* @typedef {null} EmptyEvent
	*
	*  Registered via `Builder::typ` without being referenced by a command.
	*
	* @typedef {{
	*		name: string,
	*	}} ManuallyRegistered
	* @property {string} name
	*
	* @typedef {string} MessageEvent
	* @property {string} "0"
	*
	* @typedef {PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize} PhaseSpecificRename
	* @property {PhaseSpecificRename_Serialize} Serialize
	* @property {PhaseSpecificRename_Deserialize} Deserialize
	*
	* @typedef {{
	*		deserialized_value: string,
	*	}} PhaseSpecificRename_Deserialize
	* @property {string} deserialized_value
	*
	* @typedef {{
	*		serialized_value: string,
	*	}} PhaseSpecificRename_Serialize
	* @property {string} serialized_value
	*
	* @typedef {"NotFound" | { PermissionDenied: string }} PlainError
	* @property {"NotFound"} NotFound
	* @property {{ PermissionDenied: string }} PermissionDenied
	*
	* @typedef {[number | null, number | null]} Point
	* @property {number | null} "0"
	* @property {number | null} "1"
	*
	*  A struct with a doc comment and common field shapes.
	*
	* @typedef {{
	*		userId: number,
	*		displayName: string,
	*		tags: string[],
	*		homepage: string | null,
	*		scores: { [key in string]: number },
	*	}} Profile
	* @property {number} userId
	* @property {string} displayName
	* @property {string[]} tags
	* @property {string | null} homepage
	* @property {{ [key in string]: number }} scores
	*
	* @typedef {{
	*		eventId: number,
	*		payload: string,
	*	}} StructEvent
	* @property {number} eventId
	* @property {string} payload
	*
	* @typedef {{ type: "Unit" } | { type: "Tuple"; data: string } | { type: "Struct"; data: {
	* 	id: number,
	* } }} TaggedEnum
	* @property {{ type: "Unit" }} Unit
	* @property {{ type: "Tuple"; data: string }} Tuple
	* @property {{ type: "Struct"; data: {
	* 	id: number,
	* } }} Struct
	*
	* @typedef {{ type: "Io"; data: string } | { type: "Parse"; data: {
	* 	line: number,
	* } }} TaggedError
	* @property {{ type: "Io"; data: string }} Io
	* @property {{ type: "Parse"; data: {
	* 	line: number,
	* } }} Parse
	*
	* @typedef {number | string} UntaggedEnum
	* @property {number} Number
	* @property {string} Text
	*
	* @typedef {string} Wrapper
	* @property {string} "0"
	*/

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ data: T; error: null } | { data: null; error: E }>}
  */
async function typedError(result) {
    try {
        return { data: await result, error: null };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { data: null, error: e };
    }
}

/**
 * @template T
 * @param {string} name
 * @param {(payload: T) => unknown} [serialize]
 * @param {(payload: any) => T} [deserialize]
 */
function makeEvent(name, serialize, deserialize) {
    const mapEvent = (cb) => (event) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload) => serialize ? serialize(payload) : payload;

    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, mapPayload(payload)),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, mapPayload(payload)),
    });

    return Object.assign(fn, base);
}

