// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	bigNumbers: (input: BigNumbers) => __TAURI_INVOKE<BigNumbers>("big_numbers", { input }),
};

/* Types */
export type BigNumbers = {
	unsigned: number,
	signed: number,
};

