#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use specta::Type;
use specta_typescript::Typescript;
use tauri::{async_runtime::RwLock, AppHandle, Runtime, State, Manager};
use souchy_tauri_specta::*;
use thiserror::Error;
pub mod library_service;

/// HELLO
/// WORLD
/// !!!!
#[tauri::command]
#[specta::specta]
fn hello_world(my_name: String) -> String {
    format!("Hello, {my_name}! You've been greeted from Rust!")
}

#[tauri::command]
#[specta::specta]
fn goodbye_world() -> impl Serialize + specta::Type {
    "Goodbye world :("
}

#[tauri::command]
#[specta::specta]
fn has_error() -> Result<&'static str, i32> {
    Err(32)
}

#[deprecated = "This is a deprecated function"]
#[tauri::command]
#[specta::specta]
fn deprecated() {}

mod nested {
    use super::*;

    #[tauri::command]
    #[specta::specta]
    pub fn some_struct() -> MyStruct {
        MyStruct {
            some_field: "Hello World".into(),
        }
    }

    #[derive(Serialize, specta::Type)] // For Specta support you must add the `specta::Type` derive macro.
    pub struct MyStruct {
        some_field: String,
    }
}

#[derive(Error, Debug, Serialize, Type)]
#[serde(tag = "type", content = "data")]
pub enum MyError {
    // On the frontend this variant will be "IoError" with no data.
    #[error("io error: {0}")]
    IoError(
        #[serde(skip)] // io::Error is not `Serialize` or `Type`
        #[from]
        std::io::Error,
    ),
    // On the frontend this variant will be "AnotherError" with string data.
    #[error("some other error: {0}")]
    AnotherError(String),
}

#[tauri::command]
#[specta::specta]
fn typesafe_errors_using_thiserror() -> Result<(), MyError> {
    Err(MyError::IoError(std::io::Error::new(
        std::io::ErrorKind::Other,
        "oh no!",
    )))
}

#[derive(Error, Debug, Serialize, Type)]
#[serde(tag = "type", content = "data")]
pub enum MyError2 {
    #[error("io error: {0}")]
    IoError(String),
}

impl From<std::io::Error> for MyError2 {
    fn from(error: std::io::Error) -> Self {
        Self::IoError(error.to_string())
    }
}

#[tauri::command]
#[specta::specta]
fn typesafe_errors_using_thiserror_with_value() -> Result<(), MyError2> {
    // some_method()?; // This will work because `?` does `From` conversion.

    Err(std::io::Error::new(std::io::ErrorKind::Other, "oh no!").into()) // We use `into` here to do the `From` conversion.
}

#[derive(Serialize, Deserialize, Debug, Clone, specta::Type, souchy_tauri_specta::Event)]
#[souchy_tauri_specta(event_name = "myDemoEvent")] // Optionally rename event key (for JS/TS)
pub struct DemoEvent(String);

#[derive(Serialize, Deserialize, Debug, Clone, specta::Type, souchy_tauri_specta::Event)]
pub struct EmptyEvent;

#[derive(Type)]
pub struct Custom(String);

#[derive(Type)]
pub struct Testing {
    a: String,
}


#[tauri::command]
#[specta::specta]
fn generic<T: tauri::Runtime>(_app: tauri::AppHandle<T>) {}


fn main() {
    let builder = Builder::<tauri::Wry>::new()
        .class(&["library_service::blue_struct"])
        .commands(souchy_tauri_specta::collect_commands![
            hello_world,
            goodbye_world,
            has_error,
            nested::some_struct,
            generic::<tauri::Wry>,
            deprecated,
            typesafe_errors_using_thiserror,
            typesafe_errors_using_thiserror_with_value,
            library_service::get_library,
            library_service::hello_app::<tauri::Wry>,
            library_service::add_db,
            library_service::get_db,
            // library_service::hello_generic::<String>,
            // library_service::MyTrait::my_method,
            library_service::blue_struct::instance,
            library_service::blue_struct::get_field,
            library_service::blue_struct::set_field,
        ])
        .events(souchy_tauri_specta::collect_events![crate::DemoEvent, EmptyEvent])
        .typ::<Custom>()
        .constant("universalConstant", 42);

    #[cfg(debug_assertions)]
    builder
        .export_per_file(
            Typescript::default()
                .formatter(specta_typescript::formatter::prettier)
                .header("/* eslint-disable */")
                .framework_header("/* DO NOT EDIT. AUTO-GENERATED BY SPECTA */"),
            "../src/bindings3",
        )
        .expect("Failed to export typescript bindings");

    #[cfg(debug_assertions)]
    builder
        .export(
            Typescript::default()
                .formatter(specta_typescript::formatter::prettier)
                .header("/* eslint-disable */"),
            "../src/bindings2.ts",
        )
        .expect("Failed to export typescript bindings");

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_jsdoc::JSDoc::default()
                .formatter(specta_typescript::formatter::prettier)
                .header("/* eslint-disable */"),
            "../src/bindings2-jsdoc.js",
        )
        .expect("Failed to export typescript bindings");

    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            app.manage(library_service::DbInstances::default());
            app.manage(library_service::blue_struct::BlueStructInstances::default());

            builder.mount_events(app);

            DemoEvent::listen(app, |event| {
                dbg!(event.payload);
            });

            DemoEvent("Test".to_string()).emit(app).ok();

            EmptyEvent::listen(app, |_| {
                println!("Got event from frontend!!");
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
