// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  A command with a doc comment.
	 * @param {string} myName
	 * @returns {Promise<string>}
	 */
	greet: (myName) => __TAURI_INVOKE("greet", { myName }),
	/** @returns {Promise<void>} */
	unitCommand: () => __TAURI_INVOKE("unit_command"),
	/** @returns {Promise<{ status: "ok"; data: string } | { status: "error"; error: PlainError }>} */
	plainError: () => typedError(__TAURI_INVOKE("plain_error")),
};

/* Types */
/**
	* @typedef {"NotFound" | { PermissionDenied: string }} PlainError
	* @property {"NotFound"} NotFound
	* @property {{ PermissionDenied: string }} PermissionDenied
	*/

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

