// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  A command with a doc comment. */
	greet: (myName: string) => __TAURI_INVOKE<string>("greet", { myName }),
	unitCommand: () => __TAURI_INVOKE<void>("unit_command"),
	plainError: () => typedError<string, PlainError>(__TAURI_INVOKE("plain_error")),
};

/* Types */
export type PlainError = "NotFound" | { PermissionDenied: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

