// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  HELLO
	 *  WORLD
	 *  !!!!
	 */
	helloWorld: (myName: string) => __TAURI_INVOKE<string>("hello_world", { myName }),
	asyncHelloWorld: (myName: string) => __TAURI_INVOKE<string>("async_hello_world", { myName }),
	hasError: () => typedError<string, number>(__TAURI_INVOKE("has_error")),
	someStruct: () => __TAURI_INVOKE<MyStruct>("some_struct"),
	generic: () => __TAURI_INVOKE<void>("generic"),
	/**
	 * @deprecated This is a deprecated function
	 */
	deprecated: () => __TAURI_INVOKE<void>("deprecated"),
	withChannel: (channel: Channel<number>) => __TAURI_INVOKE<void>("with_channel", { channel }),
	phaseSpecificRename: (input: PhaseSpecificRename_Deserialize) => __TAURI_INVOKE<PhaseSpecificRename_Serialize>("phase_specific_rename", { input }),
	typesafeErrorsUsingThiserror: () => typedError<null, MyError_Serialize>(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	typesafeErrorsUsingThiserrorWithValue: () => typedError<null, MyError2>(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
	semanticTypes: (arg: SemanticTypes, channel: Channel<SemanticTypes>) => __TAURI_INVOKE<SemanticTypes>("semantic_types", { arg: ({...arg,bytes:[...arg.bytes]}), channel: mapChannel(channel, (v) => ({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)})) }).then((v) => (({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)}) as typeof v)),
	goodbyeWorld: () => __TAURI_INVOKE<string>("goodbye_world"),
};

/** Events */
export const events = {
	emptyEvent: makeEvent<EmptyEvent, EmptyEvent>("empty-event"),
	myDemoEvent: makeEvent<DemoEvent, DemoEvent>("myDemoEvent"),
	semanticTypesEvent: makeEvent<SemanticTypesEvent, SemanticTypesEvent>("semantic-types-event", (v) => ({...v,bytes:[...v.bytes]}), (v) => ({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)})),
};

/* Constants */
export const universalConstant = 42 as const;

/* Types */
export type Custom = string;

export type DemoEvent = string;

export type EmptyEvent = null;

export type MyError = MyError_Serialize | MyError_Deserialize;

export type MyError2 = { type: "IoError"; data: string };

export type MyError_Deserialize = { type: "IoError"; data: null } | { type: "AnotherError"; data: string };

export type MyError_Serialize = { type: "IoError" } | { type: "AnotherError"; data: string };

export type MyStruct = {
	some_field: string,
};

export type PhaseSpecificRename = PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize;

export type PhaseSpecificRename_Deserialize = {
	deserialized_value: string,
};

export type PhaseSpecificRename_Serialize = {
	serialized_value: string,
};

export type SemanticTypes = {
	date: Date,
	bytes: Uint8Array,
	url: URL,
};

export type SemanticTypesEvent = {
	date: Date,
	bytes: Uint8Array,
	url: URL,
};

export type Testing = {
	a: string,
};

/* Tauri Specta runtime */
function mapChannel<T>(channel: Channel<T>, deserialize: (payload: any) => T): Channel<T> {
    return new Channel((payload) => channel.onmessage(deserialize(payload)));
}

async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<TListen, TEmit = TListen>(name: string, serialize?: (payload: TEmit) => unknown, deserialize?: (payload: any) => TListen) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<TListen>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: TEmit) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>
    });

    return Object.assign(fn, base);
}

/** Tanstack Query */
import { mutationOptions, queryOptions } from '@tanstack/react-query';

export const queries = {
	helloWorld: (...args: Parameters<typeof commands.helloWorld>) => queryOptions({ queryKey: ["helloWorld", ...args], queryFn: () => commands.helloWorld(...args) }),
	asyncHelloWorld: (...args: Parameters<typeof commands.asyncHelloWorld>) => queryOptions({ queryKey: ["asyncHelloWorld", ...args], queryFn: () => commands.asyncHelloWorld(...args) }),
	hasError: (...args: Parameters<typeof commands.hasError>) => queryOptions({ queryKey: ["hasError", ...args], queryFn: () => commands.hasError(...args) }),
	someStruct: (...args: Parameters<typeof commands.someStruct>) => queryOptions({ queryKey: ["someStruct", ...args], queryFn: () => commands.someStruct(...args) }),
	generic: (...args: Parameters<typeof commands.generic>) => queryOptions({ queryKey: ["generic", ...args], queryFn: () => commands.generic(...args) }),
	deprecated: (...args: Parameters<typeof commands.deprecated>) => queryOptions({ queryKey: ["deprecated", ...args], queryFn: () => commands.deprecated(...args) }),
	withChannel: (...args: Parameters<typeof commands.withChannel>) => queryOptions({ queryKey: ["withChannel", ...args], queryFn: () => commands.withChannel(...args) }),
	phaseSpecificRename: (...args: Parameters<typeof commands.phaseSpecificRename>) => queryOptions({ queryKey: ["phaseSpecificRename", ...args], queryFn: () => commands.phaseSpecificRename(...args) }),
	typesafeErrorsUsingThiserror: (...args: Parameters<typeof commands.typesafeErrorsUsingThiserror>) => queryOptions({ queryKey: ["typesafeErrorsUsingThiserror", ...args], queryFn: () => commands.typesafeErrorsUsingThiserror(...args) }),
	typesafeErrorsUsingThiserrorWithValue: (...args: Parameters<typeof commands.typesafeErrorsUsingThiserrorWithValue>) => queryOptions({ queryKey: ["typesafeErrorsUsingThiserrorWithValue", ...args], queryFn: () => commands.typesafeErrorsUsingThiserrorWithValue(...args) }),
	semanticTypes: (...args: Parameters<typeof commands.semanticTypes>) => queryOptions({ queryKey: ["semanticTypes", ...args], queryFn: () => commands.semanticTypes(...args) }),
};
export const queryKeys = {
	helloWorld: (...args: Partial<Parameters<typeof commands.helloWorld>>) => ["helloWorld", ...args],
	asyncHelloWorld: (...args: Partial<Parameters<typeof commands.asyncHelloWorld>>) => ["asyncHelloWorld", ...args],
	hasError: (...args: Partial<Parameters<typeof commands.hasError>>) => ["hasError", ...args],
	someStruct: (...args: Partial<Parameters<typeof commands.someStruct>>) => ["someStruct", ...args],
	generic: (...args: Partial<Parameters<typeof commands.generic>>) => ["generic", ...args],
	deprecated: (...args: Partial<Parameters<typeof commands.deprecated>>) => ["deprecated", ...args],
	withChannel: (...args: Partial<Parameters<typeof commands.withChannel>>) => ["withChannel", ...args],
	phaseSpecificRename: (...args: Partial<Parameters<typeof commands.phaseSpecificRename>>) => ["phaseSpecificRename", ...args],
	typesafeErrorsUsingThiserror: (...args: Partial<Parameters<typeof commands.typesafeErrorsUsingThiserror>>) => ["typesafeErrorsUsingThiserror", ...args],
	typesafeErrorsUsingThiserrorWithValue: (...args: Partial<Parameters<typeof commands.typesafeErrorsUsingThiserrorWithValue>>) => ["typesafeErrorsUsingThiserrorWithValue", ...args],
	semanticTypes: (...args: Partial<Parameters<typeof commands.semanticTypes>>) => ["semanticTypes", ...args],
};
export const mutations = {
	goodbyeWorld: () => mutationOptions({ mutationKey: ["goodbyeWorld"], mutationFn: () => commands.goodbyeWorld() }),
};
export const mutationKeys = {
	goodbyeWorld: () => ["goodbyeWorld"],
};

