// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import { queryOptions as __TANSTACK_QUERY_OPTIONS, mutationOptions as __TANSTACK_MUTATION_OPTIONS } from "@tanstack/react-query";

/** Commands */
export const commands = {
	/**
	 *  Get a user by ID.
	 * 
	 *  Returns an error if the user does not exist.
	 */
	getUser: (id: number) => typedError<User, ApiError>(__TAURI_INVOKE("get_user", { id })),
	// List all users.
	listUsers: () => __TAURI_INVOKE<User[]>("list_users"),
	/**
	 *  List todos for a specific user, optionally filtering by title.
	 * 
	 *  If `title` is provided, only todos containing that substring are returned.
	 */
	listTodos: (userId: number, title: string | null) => __TAURI_INVOKE<Todo[]>("list_todos", { userId, title }),
	createUser: (name: string, email: string) => typedError<User, ApiError>(__TAURI_INVOKE("create_user", { name, email })),
	createTodo: (title: string, userId: number) => typedError<Todo, ApiError>(__TAURI_INVOKE("create_todo", { title, userId })),
	// Delete a user by ID, returning an error if the user does not exist.
	deleteUser: (id: number) => typedError<null, ApiError>(__TAURI_INVOKE("delete_user", { id })),
	// Delete a todo by ID, returning an error if the todo does not exist.
	deleteTodo: (id: number) => typedError<null, ApiError>(__TAURI_INVOKE("delete_todo", { id })),
};

/** Query Keys */
export const queryKeys = {
	getUser: (id?: number) => filterKey(["getUser"] as const, { id }),
	listUsers: () => ["listUsers"] as const,
	listTodos: (userId?: number, title?: string | null) => filterKey(["listTodos"] as const, { userId, title }),
};

/** Queries */
export const queries = {
	/**
	 *  Get a user by ID.
	 * 
	 *  Returns an error if the user does not exist.
	 */
	getUser: (id: number) => __TANSTACK_QUERY_OPTIONS<User, ApiError>({ queryKey: queryKeys.getUser(id), queryFn: () => unwrapTypedError(commands.getUser(id)) }),
	// List all users.
	listUsers: () => __TANSTACK_QUERY_OPTIONS<User[]>({ queryKey: queryKeys.listUsers(), queryFn: () => commands.listUsers() }),
	/**
	 *  List todos for a specific user, optionally filtering by title.
	 * 
	 *  If `title` is provided, only todos containing that substring are returned.
	 */
	listTodos: (userId: number, title: string | null) => __TANSTACK_QUERY_OPTIONS<Todo[]>({ queryKey: queryKeys.listTodos(userId, title), queryFn: () => commands.listTodos(userId, title) }),
};

/** Mutation Keys */
export const mutationKeys = {
	createUser: () => ["createUser"] as const,
	createTodo: () => ["createTodo"] as const,
	deleteUser: () => ["deleteUser"] as const,
	deleteTodo: () => ["deleteTodo"] as const,
};

/** Mutations */
export const mutations = {
	createUser: () => __TANSTACK_MUTATION_OPTIONS<User, ApiError, { name: string, email: string }>({ mutationKey: mutationKeys.createUser(), mutationFn: ({ name, email }: { name: string, email: string }) => unwrapTypedError(commands.createUser(name, email)) }),
	createTodo: () => __TANSTACK_MUTATION_OPTIONS<Todo, ApiError, { title: string, userId: number }>({ mutationKey: mutationKeys.createTodo(), mutationFn: ({ title, userId }: { title: string, userId: number }) => unwrapTypedError(commands.createTodo(title, userId)) }),
	// Delete a user by ID, returning an error if the user does not exist.
	deleteUser: () => __TANSTACK_MUTATION_OPTIONS<null, ApiError, { id: number }>({ mutationKey: mutationKeys.deleteUser(), mutationFn: ({ id }: { id: number }) => unwrapTypedError(commands.deleteUser(id)) }),
	// Delete a todo by ID, returning an error if the todo does not exist.
	deleteTodo: () => __TANSTACK_MUTATION_OPTIONS<null, ApiError, { id: number }>({ mutationKey: mutationKeys.deleteTodo(), mutationFn: ({ id }: { id: number }) => unwrapTypedError(commands.deleteTodo(id)) }),
};

/* Types */
// A simple API error type for demonstration purposes.
export type ApiError = { type: "NotFound"; data: string } | { type: "Internal"; data: string };

// A todo item associated with a user.
export type Todo = {
	id: number,
	title: string,
	completed: boolean,
	user_id: number,
};

// A user of the application.
export type User = {
	id: number,
	name: string,
	email: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

async function unwrapTypedError<T, E>(result: Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>): Promise<T> {
    const v = await result;
    if (v.status === "error") throw v.error;
    return v.data;
}

function filterKey<const P extends readonly unknown[], A extends Record<string, unknown>>(prefix: P, args: A): readonly [...P] | readonly [...P, Partial<A>] {
    const filtered = Object.fromEntries(Object.entries(args).filter(([, v]) => v !== undefined));
    return Object.keys(filtered).length > 0 ? [...prefix, filtered] as const as any : [...prefix] as const;
}

