// This file has been generated by Specta. DO NOT EDIT.

type custom = string

type demoEvent = string

type emptyEvent = unit

type myError =
  | IoError
  | AnotherError(string)

type myError2 =
  | IoError(string)

type myStruct = {
  some_field: string,
}

type testing = {
  a: string,
}

type tauriChannel__<'a>

@module("@tauri-apps/api/core") external tauriInvoke__: (string, {..}) => promise<'a> = "invoke"

%%private(
  let typedError__: promise<'a> => promise<result<'a, 'e>> = async promise =>
    switch await promise {
    | exception e => Error(Obj.magic(e))
    | v => Ok(v)
    }
)

module Commands = {
  let helloWorld = (~myName: string): promise<string> =>
    tauriInvoke__("hello_world", {"myName": myName})
  let goodbyeWorld = (): promise<string> =>
    tauriInvoke__("goodbye_world", Object.make())
  let asyncHelloWorld = (~myName: string): promise<string> =>
    tauriInvoke__("async_hello_world", {"myName": myName})
  let hasError = (): promise<result<string, int>> =>
    typedError__(tauriInvoke__("has_error", Object.make()))
  let someStruct = (): promise<myStruct> =>
    tauriInvoke__("some_struct", Object.make())
  let generic = (): promise<unit> =>
    tauriInvoke__("generic", Object.make())
  let deprecated = (): promise<unit> =>
    tauriInvoke__("deprecated", Object.make())
  let withChannel = (~channel: tauriChannel__<int>): promise<unit> =>
    tauriInvoke__("with_channel", {"channel": channel})
  let typesafeErrorsUsingThiserror = (): promise<result<unit, myError>> =>
    typedError__(tauriInvoke__("typesafe_errors_using_thiserror", Object.make()))
  let typesafeErrorsUsingThiserrorWithValue = (): promise<result<unit, myError2>> =>
    typedError__(tauriInvoke__("typesafe_errors_using_thiserror_with_value", Object.make()))
}

type tauriEventCallback__<'a> = {"payload": 'a} => unit
type tauriEvent__<'a> = {
  "listen": tauriEventCallback__<'a> => promise<unit => unit>,
  "once": tauriEventCallback__<'a> => promise<unit => unit>,
  "emit": 'a => promise<unit>,
}
@module("@tauri-apps/api/event") external tauriListen__: (string, tauriEventCallback__<'a>) => promise<unit => unit> = "listen"
@module("@tauri-apps/api/event") external tauriOnce__: (string, tauriEventCallback__<'a>) => promise<unit => unit> = "once"
@module("@tauri-apps/api/event") external tauriEmit__: (string, 'a) => promise<unit> = "emit"

%%private(
  let makeEvent__ = (name: string): tauriEvent__<'a> => {
    "listen": cb => tauriListen__(name, cb),
    "once": cb => tauriOnce__(name, cb),
    "emit": payload => tauriEmit__(name, payload),
  }
)

module Events = {
  let emptyEvent: tauriEvent__<emptyEvent> = makeEvent__("empty-event")
  let myDemoEvent: tauriEvent__<demoEvent> = makeEvent__("myDemoEvent")
}

/* Constants */
let universalConstant = 42
