// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  A command with a doc comment. */
	greet: (myName: string) => __TAURI_INVOKE<string>("greet", { myName }),
	unitCommand: () => __TAURI_INVOKE<void>("unit_command"),
	asyncCommand: (delayMs: number) => __TAURI_INVOKE<number>("async_command", { delayMs }),
	manyArgs: (a: string, b: number, c: boolean, d: string[], e: string | null) => __TAURI_INVOKE<boolean>("many_args", { a, b, c, d, e }),
	echoProfile: (profile: Profile) => __TAURI_INVOKE<Profile>("echo_profile", { profile }),
	tupleTypes: (point: Point) => __TAURI_INVOKE<Wrapper>("tuple_types", { point }),
	enums: (tagged: TaggedEnum, untagged: UntaggedEnum) => __TAURI_INVOKE<TaggedEnum>("enums", { tagged, untagged }),
	phaseSpecificRename: (input: PhaseSpecificRename_Deserialize) => __TAURI_INVOKE<PhaseSpecificRename_Serialize>("phase_specific_rename", { input }),
	plainError: () => typedError<string, PlainError>(__TAURI_INVOKE("plain_error")),
	taggedError: () => typedError<Profile, TaggedError>(__TAURI_INVOKE("tagged_error")),
	nullableResult: () => typedError<string | null, PlainError>(__TAURI_INVOKE("nullable_result")),
	maybe: () => __TAURI_INVOKE<string | null>("maybe"),
	withChannel: (channel: Channel<number>) => __TAURI_INVOKE<void>("with_channel", { channel }),
	skippedArgs: (visible: string) => __TAURI_INVOKE<string>("skipped_args", { visible }),
	generic: () => __TAURI_INVOKE<void>("generic"),
	/**
	 * @deprecated This is a deprecated command
	 */
	deprecatedCommand: () => __TAURI_INVOKE<void>("deprecated_command"),
};

/** Events */
export const events = {
	emptyEvent: makeEvent<EmptyEvent, EmptyEvent>("empty-event"),
	messageEvent: makeEvent<MessageEvent, MessageEvent>("message-event"),
	structEvent: makeEvent<StructEvent, StructEvent>("struct-event"),
};

/* Constants */
export const APP_NAME = "Kitchen Sink" as const;

export const DEBUG_DEFAULT = false as const;

export const MAX_RETRIES = 3 as const;

/* Types */
export type EmptyEvent = null;

/**  Registered via `Builder::typ` without being referenced by a command. */
export type ManuallyRegistered = {
	name: string,
};

export type MessageEvent = string;

export type PhaseSpecificRename = PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize;

export type PhaseSpecificRename_Deserialize = {
	deserialized_value: string,
};

export type PhaseSpecificRename_Serialize = {
	serialized_value: string,
};

export type PlainError = "NotFound" | { PermissionDenied: string };

export type Point = [number | null, number | null];

/**  A struct with a doc comment and common field shapes. */
export type Profile = {
	userId: number,
	displayName: string,
	tags: string[],
	homepage: string | null,
	scores: { [key in string]: number },
};

export type StructEvent = {
	eventId: number,
	payload: string,
};

export type TaggedEnum = { type: "Unit" } | { type: "Tuple"; data: string } | { type: "Struct"; data: {
	id: number,
} };

export type TaggedError = { type: "Io"; data: string } | { type: "Parse"; data: {
	line: number,
} };

export type UntaggedEnum = number | string;

export type Wrapper = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

type EventEmitTo<T> = [T] extends [null] ? (target: __TAURI_EVENT.EventTarget | string) => Promise<void> : (target: __TAURI_EVENT.EventTarget | string, payload: T) => Promise<void>;

function makeEvent<TListen, TEmit = TListen>(name: string, serialize?: (payload: TEmit) => unknown, deserialize?: (payload: any) => TListen) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<TListen>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: TEmit) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>,
        emitTo: ((to: __TAURI_EVENT.EventTarget | string, payload: TEmit) => __TAURI_EVENT.emitTo(to, name, mapPayload(payload)) as unknown) as EventEmitTo<TEmit>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>,
        emitTo: ((to: __TAURI_EVENT.EventTarget | string, payload: TEmit) => target.emitTo(to, name, mapPayload(payload)) as unknown) as EventEmitTo<TEmit>
    });

    return Object.assign(fn, base);
}

