/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

import { invoke as TAURI_INVOKE } from "@tauri-apps/api";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: T extends null
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

function __makeEvent__<T>(name: string): __EventObj__<T> {
  return {
    listen: (cb) => TAURI_API_EVENT.listen(name, cb),
    once: (cb) => TAURI_API_EVENT.once(name, cb),
    emit: ((payload?: T) => TAURI_API_EVENT.emit(name, payload)) as any,
  };
}

type __Result__<T, E> = [T, undefined] | [undefined, E];

export const commands = {
  /**
   * HELLO
   * WORLD
   * !!!!
   */
  async helloWorld(myName: string): Promise<string> {
    return await TAURI_INVOKE<string>("plugin:tauri-specta|hello_world", {
      myName,
    });
  },
  async goodbyeWorld(): Promise<string> {
    return await TAURI_INVOKE<string>("plugin:tauri-specta|goodbye_world");
  },
  async hasError(): Promise<__Result__<string, number>> {
    try {
      return [
        await TAURI_INVOKE<string>("plugin:tauri-specta|has_error"),
        undefined,
      ];
    } catch (e: any) {
      if (e instanceof Error) throw e;
      else return [undefined, e];
    }
  },
  async someStruct(): Promise<MyStruct> {
    return await TAURI_INVOKE<MyStruct>("plugin:tauri-specta|some_struct");
  },
};

export const events = {
  demoEvent: __makeEvent__<DemoEvent>("demo-event"),
  emptyEvent: __makeEvent__<EmptyEvent>("empty-event"),
};

export type MyStruct = { some_field: string };
export type DemoEvent = string;
export type EmptyEvent = null;
