/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

export const commands = {
  /**
   * HELLO
   * WORLD
   * !!!!
   * @param { string } myName
   * @returns { Promise<string> }
   */
  async helloWorld(myName) {
    return await invoke()("hello_world", { myName });
  },
  /**
   * @returns { Promise<string> }
   */
  async goodbyeWorld() {
    return await invoke()("goodbye_world");
  },
  /**
   * @returns { Promise<[string, undefined] | [undefined, number]> }
   */
  async hasError() {
    try {
      return [await invoke()("has_error"), undefined];
    } catch (e) {
      if (e instanceof Error) throw e;
      else return [undefined, e];
    }
  },
  /**
   * @returns { Promise<MyStruct> }
   */
  async someStruct() {
    return await invoke()("some_struct");
  },
};

/**
 * @type {typeof __makeEvents__<{
 *   demoEvent: DemoEvent,
 *   emptyEvent: EmptyEvent
 * }>}
 */
const __typedMakeEvents__ = __makeEvents__;

export const events = __typedMakeEvents__({
  demoEvent: "demo-event",
  emptyEvent: "empty-event",
});

/**
 * @typedef { { some_field: string } } MyStruct
 */
/**
 * @typedef { string } DemoEvent
 */
/**
 * @typedef { null } EmptyEvent
 */

import { invoke as TAURI_INVOKE } from "@tauri-apps/api";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";

/**
 * @template T
 * @typedef {{
 *   listen: (
 *	   cb: TAURI_API_EVENT.EventCallback<T>
 *	 ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
 *	 once: (
 *	   cb: TAURI_API_EVENT.EventCallback<T>
 *	 ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
 *	 emit: T extends null
 *	   ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
 *     : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
 *	}} __EventObj__<T>
 */

/**
 * #template T,E
 * @typedef {[T, undefined] | [undefined, E]} __Result__
 */

/**
 * @template {Record<string, any>} T
 * @param {Record<keyof T, string>} mappings
 * @returns {{
 * 	 [K in keyof T]: __EventObj__<T[K]>;
 * }}
 */
function __makeEvents__(mappings) {
  return new Proxy(
    {},
    {
      get: (_, event) =>
        new Proxy(
          {},
          {
            get: (_, command) => {
              const name = mappings[event];

              switch (command) {
                case "listen":
                  return (arg) => TAURI_API_EVENT.listen(name, arg);
                case "once":
                  return (arg) => TAURI_API_EVENT.once(name, arg);
                case "emit":
                  return (arg) => TAURI_API_EVENT.emit(name, arg);
              }
            },
          }
        ),
    }
  );
}
