// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
  interface Window {
    __TAURI_INVOKE__<T>(
      cmd: string,
      args?: Record<string, unknown>
    ): Promise<T>;
  }
}

const invoke = window.__TAURI_INVOKE__;
export type Commands =
  | { name: "hello_world"; args: { my_name: string }; result: string }
  | { name: "goodbye_world"; args: null; result: string }
  | { name: "some_struct"; args: null; result: MyStruct };

export function helloWorld(myName: string) {
  return invoke<string>("hello_world", { myName });
}

export function goodbyeWorld() {
  return invoke<string>("goodbye_world");
}

export function someStruct() {
  return invoke<MyStruct>("some_struct");
}

export type MyStruct = { some_field: string };
