/* eslint-disable */
/* DO NOT EDIT. AUTO-GENERATED BY SPECTA */

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import { Result } from '../globals';
import { Custom, DemoEvent, EmptyEvent, Id, MyError, MyError2, MyStruct } from '../types';

export namespace nested {
	export async function someStruct() : Promise<MyStruct> {
	    return await TAURI_INVOKE("some_struct");
	}
}
