// This file has been generated by Tauri Specta. Do not edit this file manually.

import * as framework from "./index";

export type Custom = string;

export type DemoEvent = string;

export type EmptyEvent = null;

export type Testing = {
		a: string,
	};
