// This file has been generated by Tauri Specta. Do not edit this file manually.
export type Custom = string;

export type DemoEvent = string;

export type EmptyEvent = null;

export type MyError = { type: "IoError" } | { type: "AnotherError"; data: string };

export type MyError2 = { type: "IoError"; data: string };

export type PhaseSpecificRename = PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize;

export type PhaseSpecificRename_Deserialize = {
	deserialized_value: string,
};

export type PhaseSpecificRename_Serialize = {
	serialized_value: string,
};

export type SpecialTypes = SpecialTypes_Serialize | SpecialTypes_Deserialize;

export type SpecialTypes_Deserialize = {
	u128_max: bigint,
	u128_min: bigint,
	i128_max: bigint,
	i128_min: bigint,
};

export type SpecialTypes_Serialize = {
	u128_max: bigint | number,
	u128_min: bigint | number,
	i128_max: bigint | number,
	i128_min: bigint | number,
};

export type Testing = {
	a: string,
};
