// This file has been generated by Tauri Specta. Do not edit this file manually.

export type Custom = string;

export type DemoEvent = string;

export type EmptyEvent = null;

export type MyError = { type: "IoError" } | { type: "AnotherError"; data: string };

export type MyError2 = { type: "IoError"; data: string };

export type Testing = {
	a: string,
};
