// This file has been generated by Tauri Specta. Do not edit this file manually.

/**
 * @typedef {import("./tauri_specta_example_app")} tauri_specta_example_app
 */

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  HELLO
	 *  WORLD
	 *  !!!!
	 * @param {string} myName
	 * @returns {string} myName
	 */
	helloWorld: (myName) => __TAURI_INVOKE("hello_world", { myName }),
	/**
	 * @returns {string} myName
	 */
	goodbyeWorld: () => __TAURI_INVOKE("goodbye_world"),
	/**
	 * @param {string} myName
	 * @returns {string} myName
	 */
	asyncHelloWorld: (myName) => __TAURI_INVOKE("async_hello_world", { myName }),
	/**
	 * @returns {string} myName
	 */
	hasError: () => typedError(__TAURI_INVOKE("has_error")),
	/**
	 * @returns {string} myName
	 */
	someStruct: () => __TAURI_INVOKE("some_struct"),
	/**
	 * @returns {string} myName
	 */
	generic: () => __TAURI_INVOKE("generic"),
	/**
	 * @returns {string} myName
	 * @deprecated This is a deprecated function
	 */
	deprecated: () => __TAURI_INVOKE("deprecated"),
	/**
	 * @param {Channel<number>} channel
	 * @returns {string} myName
	 */
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
	/**
	 * @returns {string} myName
	 */
	typesafeErrorsUsingThiserror: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	/**
	 * @returns {string} myName
	 */
	typesafeErrorsUsingThiserrorWithValue: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
};

/** Events */
export const events = {
	/**
	 * @type {ReturnType<typeof makeEvent<tauri_specta_example_app.EmptyEvent>>}
	 */
	emptyEvent: makeEvent("empty-event"),
	/**
	 * @type {ReturnType<typeof makeEvent<tauri_specta_example_app.DemoEvent>>}
	 */
	myDemoEvent: makeEvent("myDemoEvent"),
};

/* Constants */
export const universalConstant = 42;

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 */
function makeEvent(name) {
    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, cb),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, cb),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, payload),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, cb),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, cb),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, payload),
    });

    return Object.assign(fn, base);
}
