// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	helloWorld: (myName) => __TAURI_INVOKE("hello_world", { myName }),
	hasError: () => typedError(__TAURI_INVOKE("has_error")),
	deprecated: () => __TAURI_INVOKE("deprecated"),
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
};

/** Events */
export const events = {
	emptyEvent: makeEvent("empty-event"),
	myDemoEvent: makeEvent("myDemoEvent"),
};

/* Constants */
export const universalConstant = 42;

/* Types */
import type * as tauri from "./tauri";
import type * as tauri_specta_example_app from "./tauri_specta_example_app";

export type { tauri, tauri_specta_example_app };

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 */
function makeEvent(name) {
    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, cb),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, cb),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, payload),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, cb),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, cb),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, payload),
    });

    return Object.assign(fn, base);
}
