// This file has been generated by Tauri Specta. Do not edit this file manually.

/**
 * @typedef {import("./tauri_specta_example_app")} tauri_specta_example_app
 * @typedef {import("./tauri_specta_example_app/nested")} tauri_specta_example_app$nested
 */

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 * HELLO
	 * WORLD
	 * !!!!
	 * @param {string} myName
	 * @returns {Promise<string>}
	 */
	helloWorld: (myName) => __TAURI_INVOKE("hello_world", { myName }),
	/** @returns {Promise<string>} */
	goodbyeWorld: () => __TAURI_INVOKE("goodbye_world"),
	/**
	 * @param {string} myName
	 * @returns {Promise<string>}
	 */
	asyncHelloWorld: (myName) => __TAURI_INVOKE("async_hello_world", { myName }),
	/** @returns {Promise<{ status: "ok"; data: string } | { status: "error"; error: number }>} */
	hasError: () => typedError(__TAURI_INVOKE("has_error")),
	/** @returns {Promise<tauri_specta_example_app$nested.MyStruct>} */
	someStruct: () => __TAURI_INVOKE("some_struct"),
	/** @returns {Promise<void>} */
	generic: () => __TAURI_INVOKE("generic"),
	/**
	 * @returns {Promise<void>}
	 * @deprecated This is a deprecated function
	 */
	deprecated: () => __TAURI_INVOKE("deprecated"),
	/**
	 * @param {Channel<number>} channel
	 * @returns {Promise<void>}
	 */
	withChannel: (channel) => __TAURI_INVOKE("with_channel", { channel }),
	/**
	 * @param {tauri_specta_example_app.PhaseSpecificRename_Deserialize} input
	 * @returns {Promise<tauri_specta_example_app.PhaseSpecificRename_Serialize>}
	 */
	phaseSpecificRename: (input) => __TAURI_INVOKE("phase_specific_rename", { input }),
	/** @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: tauri_specta_example_app.MyError }>} */
	typesafeErrorsUsingThiserror: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror")),
	/** @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: tauri_specta_example_app.MyError2 }>} */
	typesafeErrorsUsingThiserrorWithValue: () => typedError(__TAURI_INVOKE("typesafe_errors_using_thiserror_with_value")),
	/**
	 * @param {tauri_specta_example_app.SemanticTypes} arg
	 * @param {Channel<tauri_specta_example_app.SemanticTypes>} channel
	 * @returns {Promise<tauri_specta_example_app.SemanticTypes>}
	 */
	semanticTypes: (arg, channel) => __TAURI_INVOKE("semantic_types", { arg: ({...arg,bytes:[...arg.bytes]}), channel: mapChannel(channel, (v) => ({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)})) }).then((v) => ({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)})),
};

/** Events */
export const events = {
	/** @type {ReturnType<typeof makeEvent<tauri_specta_example_app.EmptyEvent>>} */
	emptyEvent: makeEvent("empty-event"),
	/** @type {ReturnType<typeof makeEvent<tauri_specta_example_app.DemoEvent>>} */
	myDemoEvent: makeEvent("myDemoEvent"),
	/** @type {ReturnType<typeof makeEvent<tauri_specta_example_app.SemanticTypesEvent>>} */
	semanticTypesEvent: makeEvent("semantic-types-event", (v) => ({...v,bytes:[...v.bytes]}), (v) => ({...v,date:new Date(v.date),bytes:new Uint8Array(v.bytes),url:new URL(v.url)})),
};

/* Constants */
export const universalConstant = 42;

/* Tauri Specta runtime */
/**
 * @template T
 * @param {Channel<T>} channel
 * @param {(payload: any) => T} deserialize
 * @returns {Channel<T>}
 */
function mapChannel(channel, deserialize) {
    return new Channel((payload) => channel.onmessage(deserialize(payload)));
}

/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 * @param {(payload: T) => unknown} [serialize]
 * @param {(payload: any) => T} [deserialize]
 */
function makeEvent(name, serialize, deserialize) {
    const mapEvent = (cb) => (event) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload) => serialize ? serialize(payload) : payload;

    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, mapPayload(payload)),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, mapPayload(payload)),
    });

    return Object.assign(fn, base);
}
