// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	* @typedef {string} Custom
	* @property {string} "0"
	*
	* @typedef {string} DemoEvent
	* @property {string} "0"
	*
	* @typedef {null} EmptyEvent
	*
	* @typedef {{ type: "IoError" } | { type: "AnotherError"; data: string }} MyError
	* @property {{ type: "IoError" }} IoError
	* @property {{ type: "AnotherError"; data: string }} AnotherError
	*
	* @typedef {{ type: "IoError"; data: string }} MyError2
	* @property {{ type: "IoError"; data: string }} IoError
	*
	* @typedef {PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize} PhaseSpecificRename
	* @property {PhaseSpecificRename_Serialize} Serialize
	* @property {PhaseSpecificRename_Deserialize} Deserialize
	*
	* @typedef {{
	*		deserialized_value: string,
	*	}} PhaseSpecificRename_Deserialize
	* @property {string} deserialized_value
	*
	* @typedef {{
	*		serialized_value: string,
	*	}} PhaseSpecificRename_Serialize
	* @property {string} serialized_value
	*
	* @typedef {{
	*		a: string,
	*	}} Testing
	* @property {string} a
	*/
