// This file has been generated by Tauri Specta. Do not edit this file manually.

import * as framework from "./index";

/**
	* @typedef {string} Custom
	*/
/**
	* @typedef {string} DemoEvent
	*/
/**
	* @typedef {null} EmptyEvent
	*/
/**
	* @typedef {{
	*		a: string,
	*	}} Testing
	*/