// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	* @typedef {string} Custom
	* @property {string} "0"
	*
	* @typedef {string} DemoEvent
	* @property {string} "0"
	*
	* @typedef {null} EmptyEvent
	*
	* @typedef {MyError_Serialize | MyError_Deserialize} MyError
	* @property {MyError_Serialize} Serialize
	* @property {MyError_Deserialize} Deserialize
	*
	* @typedef {{ type: "IoError"; data: string }} MyError2
	* @property {{ type: "IoError"; data: string }} IoError
	*
	* @typedef {{ type: "IoError"; data: null } | { type: "AnotherError"; data: string }} MyError_Deserialize
	* @property {{ type: "IoError"; data: null }} IoError
	* @property {{ type: "AnotherError"; data: string }} AnotherError
	*
	* @typedef {{ type: "IoError" } | { type: "AnotherError"; data: string }} MyError_Serialize
	* @property {{ type: "IoError" }} IoError
	* @property {{ type: "AnotherError"; data: string }} AnotherError
	*
	* @typedef {PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize} PhaseSpecificRename
	* @property {PhaseSpecificRename_Serialize} Serialize
	* @property {PhaseSpecificRename_Deserialize} Deserialize
	*
	* @typedef {{
	*		deserialized_value: string,
	*	}} PhaseSpecificRename_Deserialize
	* @property {string} deserialized_value
	*
	* @typedef {{
	*		serialized_value: string,
	*	}} PhaseSpecificRename_Serialize
	* @property {string} serialized_value
	*
	* @typedef {{
	*		date: Date,
	*		bytes: Uint8Array,
	*		url: URL,
	*	}} SemanticTypes
	* @property {Date} date
	* @property {Uint8Array} bytes
	* @property {URL} url
	*
	* @typedef {{
	*		date: Date,
	*		bytes: Uint8Array,
	*		url: URL,
	*	}} SemanticTypesEvent
	* @property {Date} date
	* @property {Uint8Array} bytes
	* @property {URL} url
	*
	* @typedef {{
	*		a: string,
	*	}} Testing
	* @property {string} a
	*/
