// This file has been generated by Tauri Specta. Do not edit this file manually.

import type * as kitchen_sink from "./kitchen_sink";

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  A command with a doc comment. */
	greet: (myName: string) => __TAURI_INVOKE<string>("greet", { myName }),
	unitCommand: () => __TAURI_INVOKE<void>("unit_command"),
	asyncCommand: (delayMs: number) => __TAURI_INVOKE<number>("async_command", { delayMs }),
	manyArgs: (a: string, b: number, c: boolean, d: string[], e: string | null) => __TAURI_INVOKE<boolean>("many_args", { a, b, c, d, e }),
	echoProfile: (profile: kitchen_sink.Profile) => __TAURI_INVOKE<kitchen_sink.Profile>("echo_profile", { profile }),
	tupleTypes: (point: kitchen_sink.Point) => __TAURI_INVOKE<kitchen_sink.Wrapper>("tuple_types", { point }),
	enums: (tagged: kitchen_sink.TaggedEnum, untagged: kitchen_sink.UntaggedEnum) => __TAURI_INVOKE<kitchen_sink.TaggedEnum>("enums", { tagged, untagged }),
	phaseSpecificRename: (input: kitchen_sink.PhaseSpecificRename_Deserialize) => __TAURI_INVOKE<kitchen_sink.PhaseSpecificRename_Serialize>("phase_specific_rename", { input }),
	plainError: () => typedError<string, kitchen_sink.PlainError>(__TAURI_INVOKE("plain_error")),
	taggedError: () => typedError<kitchen_sink.Profile, kitchen_sink.TaggedError>(__TAURI_INVOKE("tagged_error")),
	nullableResult: () => typedError<string | null, kitchen_sink.PlainError>(__TAURI_INVOKE("nullable_result")),
	maybe: () => __TAURI_INVOKE<string | null>("maybe"),
	withChannel: (channel: Channel<number>) => __TAURI_INVOKE<void>("with_channel", { channel }),
	skippedArgs: (visible: string) => __TAURI_INVOKE<string>("skipped_args", { visible }),
	generic: () => __TAURI_INVOKE<void>("generic"),
	/**
	 * @deprecated This is a deprecated command
	 */
	deprecatedCommand: () => __TAURI_INVOKE<void>("deprecated_command"),
};

/** Events */
export const events = {
	emptyEvent: makeEvent<kitchen_sink.EmptyEvent, kitchen_sink.EmptyEvent>("empty-event"),
	messageEvent: makeEvent<kitchen_sink.MessageEvent, kitchen_sink.MessageEvent>("message-event"),
	structEvent: makeEvent<kitchen_sink.StructEvent, kitchen_sink.StructEvent>("struct-event"),
};

/* Constants */
export const APP_NAME = "Kitchen Sink" as const;

export const DEBUG_DEFAULT = false as const;

export const MAX_RETRIES = 3 as const;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

type EventEmitTo<T> = [T] extends [null] ? (target: __TAURI_EVENT.EventTarget | string) => Promise<void> : (target: __TAURI_EVENT.EventTarget | string, payload: T) => Promise<void>;

function makeEvent<TListen, TEmit = TListen>(name: string, serialize?: (payload: TEmit) => unknown, deserialize?: (payload: any) => TListen) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<TListen>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: TEmit) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>,
        emitTo: ((to: __TAURI_EVENT.EventTarget | string, payload: TEmit) => __TAURI_EVENT.emitTo(to, name, mapPayload(payload)) as unknown) as EventEmitTo<TEmit>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>,
        emitTo: ((to: __TAURI_EVENT.EventTarget | string, payload: TEmit) => target.emitTo(to, name, mapPayload(payload)) as unknown) as EventEmitTo<TEmit>
    });

    return Object.assign(fn, base);
}
