// This file has been generated by Tauri Specta. Do not edit this file manually.
export type EmptyEvent = null;

/**  Registered via `Builder::typ` without being referenced by a command. */
export type ManuallyRegistered = {
	name: string,
};

export type MessageEvent = string;

export type PhaseSpecificRename = PhaseSpecificRename_Serialize | PhaseSpecificRename_Deserialize;

export type PhaseSpecificRename_Deserialize = {
	deserialized_value: string,
};

export type PhaseSpecificRename_Serialize = {
	serialized_value: string,
};

export type PlainError = "NotFound" | { PermissionDenied: string };

export type Point = [number | null, number | null];

/**  A struct with a doc comment and common field shapes. */
export type Profile = {
	userId: number,
	displayName: string,
	tags: string[],
	homepage: string | null,
	scores: { [key in string]: number },
};

export type StructEvent = {
	eventId: number,
	payload: string,
};

export type TaggedEnum = { type: "Unit" } | { type: "Tuple"; data: string } | { type: "Struct"; data: {
	id: number,
} };

export type TaggedError = { type: "Io"; data: string } | { type: "Parse"; data: {
	line: number,
} };

export type UntaggedEnum = number | string;

export type Wrapper = string;
