// This file has been generated by Tauri Specta. Do not edit this file manually.

import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Events */
export const events = {
	/** @type {ReturnType<typeof makeEvent<EmptyEvent>>} */
	emptyEvent: makeEvent("empty-event"),
	/** @type {ReturnType<typeof makeEvent<StructEvent>>} */
	structEvent: makeEvent("struct-event"),
};

/* Types */
/**
	* @typedef {null} EmptyEvent
	*
	* @typedef {{
	*		eventId: number,
	*		payload: string,
	*	}} StructEvent
	* @property {number} eventId
	* @property {string} payload
	*/

/* Tauri Specta runtime */
/**
 * @template T
 * @param {string} name
 * @param {(payload: T) => unknown} [serialize]
 * @param {(payload: any) => T} [deserialize]
 */
function makeEvent(name, serialize, deserialize) {
    const mapEvent = (cb) => (event) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload) => serialize ? serialize(payload) : payload;

    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, mapPayload(payload)),
        /**
         * @param {__TAURI_EVENT.EventTarget | string} to
         * @param {T} payload
         */
        emitTo: (to, payload) => __TAURI_EVENT.emitTo(to, name, mapPayload(payload)),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, mapPayload(payload)),
        /**
         * @param {__TAURI_EVENT.EventTarget | string} to
         * @param {T} payload
         */
        emitTo: (to, payload) => target.emitTo(to, name, mapPayload(payload)),
    });

    return Object.assign(fn, base);
}

