/* eslint-disable */
/* DO NOT EDIT. AUTO-GENERATED BY SPECTA */

import { __makeEvents__ } from './globals';
import { Custom, DemoEvent, EmptyEvent, MyError, MyError2, MyStruct } from './types';

export const events = __makeEvents__<{
	emptyEvent: EmptyEvent,
	myDemoEvent: DemoEvent
}>({
	emptyEvent: "empty-event",
	myDemoEvent: "myDemoEvent"
})